language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
# Bundler+Rubygems issue; see https://github.com/travis-ci/travis-ci/issues/8978
before_install:
  - gem update --system
